# Generated by Django 3.2.13 on 2022-08-06 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locks_task_2', '0002_account_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='version',
        ),
    ]
