# Generated by Django 3.2.13 on 2022-08-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locks_task_2', '0003_remove_account_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
